---
application:
  name: "deck-project"
  project: "deck_proj"
  organization: "QoveryCommunity"
routers:
- name: "main-deck-project"
  routes:
  - application_name: "deck-project"
    paths:
    - "/*"
